### ISSUE TITLE
[Console] test paramètres enroll 

### ISSUE THREAD

**Issue by sraillard** [passmanSA/com.zsmartsystems.zigbee#31]
Si le paramètre passé est incorrect, il n'y a aucune erreur (par exemple, nodeid inconnu ou sans le endpoint) : 
```
> enroll 3471/1
> enroll 3471
```

Et l'aide en ligne est incorrecte, c'est le ENDPOINT qu'il faut passer : 
```
> help enroll
Enrolls IAS Zone device to this CIE device by setting own address as CIE address to the  IAS Zone device.

Syntax: enroll DEVICEID
```

**Comment by mikomarrache** [comment]
J'ai cree une PR pour ce ticket:

https://github.com/passmanSA/com.zsmartsystems.zigbee/pull/32

J'ai ajoute un message d'erreur si le node n'existe pas ou si l'endpoint n'existe pas. Il n'y a pas de validation sur aucune des commandes, du coup, pas de message indiquant que le parametre est invalide.
