### ISSUE TITLE
[Console] Chek-in response non envoyée

### ISSUE THREAD

**Issue by sraillard** [passmanSA/com.zsmartsystems.zigbee#38]
Dans la dernière version de la console, la response check-in n'est plus envoyée (on pouvait choisir la réponse avec la commande 
setcheckintimeout).

![image](https://github.com/passmanSA/com.zsmartsystems.zigbee/assets/32952986/4387e6ae-110c-46e1-b5b0-abeea9d26ca2)

**Comment by mikomarrache** [comment]
Est ce que tu vois cette ligne de log:

`[ZclPollControlClient] Received command`

**Comment by sraillard** [comment]
au moment de l'arrivée d'un check-in, je n'ai que ça : 
19:21:18.812  DEBUG  RX EZSP: EzspIncomingMessageHandler [networkId=0, type=EMBER_INCOMING_UNICAST, apsFrame=EmberApsFrame [profileId=0104, clusterId=0020, sourceEndpoint=1, destinationEndpoint=1, options=[EMBER_APS_OPTION_RETRY, EMBER_APS_OPTION_ENABLE_ROUTE_DISCOVERY], groupId=0, sequence=06], lastHopLqi=172, lastHopRssi=-57, sender=12F4, bindingIndex=255, addressIndex=255, messageContents=19 45 00]
19:21:18.813  DEBUG  [COM22] RX EZSP: EzspIncomingMessageHandler [networkId=0, type=EMBER_INCOMING_UNICAST, apsFrame=EmberApsFrame [profileId=0104, clusterId=0020, sourceEndpoint=1, destinationEndpoint=1, options=[EMBER_APS_OPTION_RETRY, EMBER_APS_OPTION_ENABLE_ROUTE_DISCOVERY], groupId=0, sequence=06], lastHopLqi=172, lastHopRssi=-57, sender=12F4, bindingIndex=255, addressIndex=255, messageContents=19 45 00]
19:21:18.813  DEBUG  RX APS: ZigBeeApsFrame [sourceAddress=12F4/1, destinationAddress=0000/1, profile=0104, cluster=0020, addressMode=DEVICE, radius=0, apsSecurity=false, ackRequest=false, apsCounter=06, rssi=-57, lqi=AC, payload=19 45 00]
```
19:21:18.814  DEBUG  [COM22] RX APS: ZigBeeApsFrame [sourceAddress=12F4/1, destinationAddress=0000/1, profile=0104, cluster=0020, addressMode=DEVICE, radius=0, apsSecurity=false, ackRequest=false, apsCounter=06, rssi=-57, lqi=AC, payload=19 45 00]
19:21:18.814  DEBUG  3C6A2CFFFED3C855: Node update. NWK Address=12F4
19:21:18.814  DEBUG  3C6A2CFFFED3C855: Node 12F4 is not updated
19:21:18.815  DEBUG  RX ZCL: ZclHeader [frameType=CLUSTER_SPECIFIC_COMMAND, manufacturerSpecific=false, direction=SERVER_TO_CLIENT, disableDefaultResponse=true, manufacturerCode=0, sequenceNumber=69, commandId=0]
19:21:18.815  DEBUG  [COM22] RX ZCL: ZclHeader [frameType=CLUSTER_SPECIFIC_COMMAND, manufacturerSpecific=false, direction=SERVER_TO_CLIENT, disableDefaultResponse=true, manufacturerCode=0, sequenceNumber=69, commandId=0]
19:21:18.816  DEBUG  RX CMD: CheckInCommand [Poll Control: 12F4/1 -> 0000/1, cluster=0020, TID=45]
19:21:18.816  DEBUG  [COM22] RX CMD: CheckInCommand [Poll Control: 12F4/1 -> 0000/1, cluster=0020, TID=45]
19:21:18.816  DEBUG  notifyTransactionCommand: CheckInCommand [Poll Control: 12F4/1 -> 0000/1, cluster=0020, TID=45] 
```
